### ISSUE TITLE
bug: Getting error in docker - 'exec ./jiotv_go: exec format error'

### ISSUE THREAD

**Issue by niravjdn** [rabilrbl/jiotv_go#231]
### Bug description

I'm trying to run it on raspberry pi which is arm based. Below is my docker compose and below is the error,

### Steps to reproduce

1. Put this stack in portainer or run it through command line.

```
version: '3'
services:
  jiotv_go:
    image: ghcr.io/rabilrbl/jiotv_go
    ports:
      - "5053:5001"
    volumes:
      - /DATA/AppData/JIO-TV/.jiotv_go/secrets:/app/secrets
```

### Relevant log output

```shell
exec ./jiotv_go: exec format error
```

### Screenshots or videos

![image](https://github.com/rabilrbl/jiotv_go/assets/11633329/e34398f3-0917-41fc-9f04-cb1de55821f6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
