### ISSUE TITLE
bug: EPG not available in tivimate and iptv smarters

### ISSUE THREAD

**Issue by h4wwk3ye** [rabilrbl/jiotv_go#309]
### Bug description

I have tried both the apps, and the EPG is not available in any of them. I can see the guide on the website however.

Running it in docker with the following compose
```
  jiotv_go:
    container_name: jiotv
    ports:
      - 5001:5001
    environment:
      - JIOTV_EPG=true
      - JIOTV_DRM=true
    volumes:
        - ${CONFIG_DIR}/jiotv_go/secrets:/app/secrets
    image: ghcr.io/rabilrbl/jiotv_go
    restart: ${RESTART_MODE}
```

### Steps to reproduce

Add M3U and EPG url in the apps. EFP won't be available.

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
